export const CREATE_REPLY_REQUEST = "CREATE_REPLY_REQUEST";
export const CREATE_REPLY_SUCCESS = "CREATE_REPLY_SUCCESS";
export const CREATE_REPLY_FAIL = "CREATE_REPLY_FAIL";
export const CREATE_REPLY_RESET = "CREATE_REPLY_RESET";

export const UPDATE_REPLY_REQUEST = "UPDATE_REPLY_REQUEST";
export const UPDATE_REPLY_SUCCESS = "UPDATE_REPLY_SUCCESS";
export const UPDATE_REPLY_FAIL = "UPDATE_REPLY_FAIL";
export const UPDATE_REPLY_RESET = "UPDATE_REPLY_RESET";

export const DELETE_REPLY_REQUEST = "DELETE_REPLY_REQUEST";
export const DELETE_REPLY_SUCCESS = "DELETE_REPLY_SUCCESS";
export const DELETE_REPLY_FAIL = "DELETE_REPLY_FAIL";
export const DELETE_REPLY_RESET = "DELETE_REPLY_RESET";

export const LIKE_REPLY_REQUEST = "LIKE_REPLY_REQUEST";
export const LIKE_REPLY_SUCCESS = "LIKE_REPLY_SUCCESS";
export const LIKE_REPLY_FAIL = "LIKE_REPLY_FAIL";
export const LIKE_REPLY_RESET = "LIKE_REPLY_RESET";

export const CREATE_COMMENT_REQUEST = "CREATE_COMMENT_REQUEST";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const CREATE_COMMENT_FAIL = "CREATE_COMMENT_FAIL";
export const CREATE_COMMENT_RESET = "CREATE_COMMENT_RESET";

export const UPDATE_COMMENT_REQUEST = "UPDATE_COMMENT_REQUEST";
export const UPDATE_COMMENT_SUCCESS = "UPDATE_COMMENT_SUCCESS";
export const UPDATE_COMMENT_FAIL = "UPDATE_COMMENT_FAIL";
export const UPDATE_COMMENT_RESET = "UPDATE_COMMENT_RESET";

export const DELETE_COMMENT_REQUEST = "DELETE_COMMENT_REQUEST";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_FAIL = "DELETE_COMMENT_FAIL";
export const DELETE_COMMENT_RESET = "DELETE_COMMENT_RESET";

export const LIKE_COMMENT_REQUEST = "LIKE_COMMENT_REQUEST";
export const LIKE_COMMENT_SUCCESS = "LIKE_COMMENT_SUCCESS";
export const LIKE_COMMENT_FAIL = "LIKE_COMMENT_FAIL";
export const LIKE_COMMENT_RESET = "LIKE_COMMENT_RESET";
